version: '3.9'

services:
  product-service-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: product-service
      POSTGRES_PASSWORD: prod
    volumes:
      - product-service-db-data:/var/lib/postgresql/data
    networks:
      - octo-umbrella

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - discovery-service
      - product-service-db
    environment:
      CONFIG_URL: "http://config-service:8888"
      EUREKA_URL: "http://discovery-service:8761/eureka"
      DATASOURCE_USERNAME: "product-service"
      DATASOURCE_PASSWORD: "prod"
      DATASOURCE_URL: "product-service-db:5432"
      DATASOURCE_NAME: "products"
    networks:
      - octo-umbrella

  order-service-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: order-service
      POSTGRES_PASSWORD: order
    volumes:
      - order-service-db-data:/var/lib/postgresql/data
    networks:
      - octo-umbrella

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - discovery-service
      - order-service-db
    environment:
      CONFIG_URL: "http://config-service:8888"
      EUREKA_URL: "http://discovery-service:8761/eureka"
      DATASOURCE_USERNAME: "order-service"
      DATASOURCE_PASSWORD: "order"
      DATASOURCE_URL: "order-service-db:5432"
      DATASOURCE_NAME: "orders"
    networks:
      - octo-umbrella

  user-service-db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 54323:5432
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user-service
      POSTGRES_PASSWORD: user
    volumes:
      - user-service-db-data:/var/lib/postgresql/data
    networks:
      - octo-umbrella

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - discovery-service
      - user-service-db
    environment:
      CONFIG_URL: "http://config-service:8888"
      EUREKA_URL: "http://discovery-service:8761/eureka"
      DATASOURCE_USERNAME: "user-service"
      DATASOURCE_PASSWORD: "user"
      DATASOURCE_URL: "user-service-db:5432"
      DATASOURCE_NAME: "users"
    networks:
      - octo-umbrella

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    restart: unless-stopped
    networks:
      - octo-umbrella

  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    restart: unless-stopped
    networks:
      - octo-umbrella

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      EUREKA_URL: "http://discovery-service:8761/eureka"
    depends_on:
      - discovery-service
      - product-service
      - order-service
      - user-service
    networks:
      - octo-umbrella

volumes:
  product-service-db-data:
  order-service-db-data:
  user-service-db-data:

networks:
  octo-umbrella:
    driver: bridge