server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true